name: Azure Deploy

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    paths:
      - infrastructure/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        uses: azure/cli@v2
        with:
          inline-script: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME}} --location ${{vars.RESOURCE_GROUP_LOCATION}}
            echo "Azure Resource Group created"

      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep
          
